Plot:

    Line plot - years X crime type

In [1]:
import pandas as pd
import plotly.graph_objects as go
from plotly.subplots import make_subplots

In [2]:
crime = pd.read_csv('data/Crime_Data_from_2010_to_2019.csv')

In [3]:
crime['Crm Cd Desc'].value_counts().head(15)

BATTERY - SIMPLE ASSAULT                                    190537
BURGLARY FROM VEHICLE                                       162174
VEHICLE - STOLEN                                            159882
THEFT PLAIN - PETTY ($950 & UNDER)                          149860
BURGLARY                                                    147695
THEFT OF IDENTITY                                           127834
INTIMATE PARTNER - SIMPLE ASSAULT                           114551
VANDALISM - FELONY ($400 & OVER, ALL CHURCH VANDALISMS)     109449
ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT               92717
VANDALISM - MISDEAMEANOR ($399 OR UNDER)                     90431
THEFT FROM MOTOR VEHICLE - PETTY ($950 & UNDER)              88497
ROBBERY                                                      83858
THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LIVESTK,PROD     74604
CRIMINAL THREATS - NO WEAPON DISPLAYED                       56650
SHOPLIFTING - PETTY THEFT ($950 & UNDER)                     48396
Name: Crm Cd Desc, dtype: int64

In [4]:
topCrm = crime['Crm Cd Desc'].value_counts()[:10].index.tolist()

In [5]:
crime = crime[crime['Crm Cd Desc'].isin(topCrm)]

In [6]:
crimeDF = crime[['DATE OCC', 'AREA NAME', 'Crm Cd Desc']].copy()

In [7]:
crimeDF.loc[:, 'DATE'] = crimeDF['DATE OCC'].apply(lambda x: x.split()[0])
crimeDF.loc[:, 'DATE'] = pd.to_datetime(crimeDF['DATE'], format = '%m/%d/%Y')
crimeDF.drop(columns=['DATE OCC'], inplace=True)

In [8]:
crimeDF['DATE'] = crimeDF['DATE'].apply(lambda x: x.strftime('%Y-%m'))
crimeDF.head()

   AREA NAME                                        Crm Cd Desc     DATE
1    Pacific  VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...  2010-09
6    Central                              BURGLARY FROM VEHICLE  2010-01
7    Central     ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT  2010-01
8    Central     ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT  2010-01
10   Central                           BATTERY - SIMPLE ASSAULT  2010-01

In [9]:
dic = {'BATTERY - SIMPLE ASSAULT': 'Simple assault', 'BURGLARY FROM VEHICLE': 'Burglary from vehicle', 'VEHICLE - STOLEN': 'Stolen vehicle',
       'THEFT PLAIN - PETTY ($950 & UNDER)': 'Small theft (under 950$)', 'BURGLARY': 'Burglary', 'THEFT OF IDENTITY' : 'Teft of identity',
       'INTIMATE PARTNER - SIMPLE ASSAULT' :'Intimate partner assault', 'VANDALISM - FELONY ($400 & OVER, ALL CHURCH VANDALISMS)' : 'Vandalism (felony)',
       'ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT' : 'Agravated assault', 'VANDALISM - MISDEAMEANOR ($399 OR UNDER)': 'Vandalism (misdeameanor)'
      }

In [10]:
crimeDF.replace({"Crm Cd Desc": dic}, inplace=True)
crimeDF.rename(columns={"AREA NAME": "Area", "Crm Cd Desc": "Crime", "DATE": "Date"}, inplace=True)
crimeDF.head()

       Area                  Crime     Date
1   Pacific     Vandalism (felony)  2010-09
6   Central  Burglary from vehicle  2010-01
7   Central      Agravated assault  2010-01
8   Central      Agravated assault  2010-01
10  Central         Simple assault  2010-01

In [11]:
crimeDF.rename(columns={"AREA NAME": "Area", "Crm Cd Desc": "Crime", "DATE": "Date"}, inplace=True)

In [12]:
crimeTypesDF = crimeDF.pivot_table(index=['Date', 'Area'], columns='Crime', aggfunc='size').rename_axis(None, axis=1)
crimeTypesDF.reset_index(level=['Date', 'Area'], inplace=True)
crimeTypesDF.fillna(0)
crimeTypesDF.head()

,Date,Area,Agravated assault,Burglary,Burglary from vehicle,Intimate partner assault,Simple assault,Small theft (under 950$),Stolen vehicle,Teft of identity,Vandalism (felony),Vandalism (misdeameanor)
0,2010-01,77th Street,88,85,89,60,160,63,92,103,46,58
1,2010-01,Central,29,13,67,24,109,55,17,49,14,15
2,2010-01,Devonshire,15,94,108,44,65,47,71,88,42,54
3,2010-01,Foothill,32,56,96,56,56,38,75,131,43,41
4,2010-01,Harbor,14,84,43,48,48,51,84,115,40,42

In [13]:
crimeTypesDF.to_csv('crimeTypes.csv')

In [21]:
crimeTypesDF = pd.read_csv('crimeTypes.csv')

In [36]:
crimeTypesDF['Date'].str.split('-')[0]

['2010', '01']

In [39]:
crimeTypesDF[crimeTypesDF['Date'].str.contains('2010')]

,Unnamed: 0,Date,Area,Agravated assault,Burglary,Burglary from vehicle,Intimate partner assault,Simple assault,Small theft (under 950$),Stolen vehicle,Teft of identity,Vandalism (felony),Vandalism (misdeameanor)
0,0,2010-01,77th Street,88,85,89,60,160,63,92,103,46,58
1,1,2010-01,Central,29,13,67,24,109,55,17,49,14,15
2,2,2010-01,Devonshire,15,94,108,44,65,47,71,88,42,54
3,3,2010-01,Foothill,32,56,96,56,56,38,75,131,43,41
4,4,2010-01,Harbor,14,84,43,48,48,51,84,115,40,42
...,...,...,...,...,...,...,...,...,...,...,...,...,...
247,247,2010-12,Topanga,20,70,75,29,64,52,52,58,41,31
248,248,2010-12,Van Nuys,9,57,95,56,48,54,55,64,41,29
249,249,2010-12,West LA,7,72,100,20,45,71,30,76,25,42
250,250,2010-12,West Valley,14,99,73,33,57,43,49,56,39,36
251,251,2010-12,Wilshire,20,81,94,19,48,25,47,59,25,29

In [40]:
import plotly.io as pio

def lineplot_crimeTypes(year, area):
    ctData = crimeTypesDF[(crimeTypesDF['Date'].str.contains(year))&(crimeTypesDF['Area'] == area)]
    data_sectors = [dict(
      type = 'scatter',
      x = ctData['Date'],
      y = ctData["Burglary"],
      transforms = [dict(
        type = 'aggregate',
        groups = ctData['Date'],
        aggregations = [dict(
            target = 'y', func = 'sum', enabled = True),
        ]
      )]
    )]

    layout_sectors = dict(title=dict(text='Number of Crimes'),
                          xaxis=dict(title='Date'),
                          yaxis=dict(title='# of crime'),
                          paper_bgcolor='rgba(0,0,0,0)',
                          plot_bgcolor='rgba(0,0,0,0)',)

    fig_dict = dict(data=data_sectors, layout=layout_sectors)

    pio.show(fig_dict, validate=False)

In [41]:
lineplot_crimeTypes('2011', 'Harbor')

In [ ]:
crimeAreas_list = crimeAreaDF.columns

# try:
#     init_date = init_dates.rsplit('-', 1)[0]
#     final_date = final_date.rsplit('-', 1)[0]
# except:
#     init_date = '2009-12-31'.rsplit('-', 1)[0]
#     final_date = '20020-12-31'.rsplit('-', 1)[0]
    

# tempCrimeAreas = crimeAreaDF.copy()
# tempCrimeAreas = tempCrimeAreas[(tempCrimeAreas.index > init_date) & (tempCrimeAreas.index < final_date)]

data_crimeAreas = [dict(type='scatter',
                     x=crimeAreaDF.index,
                     y=crimeAreaDF[crimeArea],
                     name=crimeArea)
                            for crimeArea in crimeAreas_list]

layout_crimeAreas = dict(title=dict(text='Number of Crimes'),
                      xaxis=dict(title='Date'),
                      yaxis=dict(title='# of crime'),
                      paper_bgcolor='rgba(0,0,0,0)',
                      plot_bgcolor='rgba(0,0,0,0)',)

fig_sectors = go.Figure(data=data_crimeAreas, layout=layout_crimeAreas)

fig_sectors.show()

In [ ]:
# assault = ['BATTERY - SIMPLE ASSAULT', 'INTIMATE PARTNER - SIMPLE ASSAULT', 'ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT', 
#            'ROBBERY', 'CRIMINAL THREATS - NO WEAPON DISPLAYED', 'BRANDISH WEAPON', 'INTIMATE PARTNER - AGGRAVATED ASSAULT', 'ATTEMPTED ROBBERY', 
#           'BATTERY WITH SEXUAL CONTACT', 'RAPE, FORCIBLE', 'BUNCO, GRAND THEFT', 'BATTERY POLICE (SIMPLE)',
#           'CRM AGNST CHLD (13 OR UNDER) (14-15 & SUSP 10 YRS OLDER)', 'SEX,UNLAWFUL(INC MUTUAL CONSENT, PENETRATION W/ FRGN OBJ', 
#           'OTHER ASSAULT', 'SEXUAL PENETRATION W/FOREIGN OBJECT', 'EXTORTION', 'SHOTS FIRED AT INHABITED DWELLING', 'KIDNAPPING',
#            'ORAL COPULATION', 'SEX OFFENDER REGISTRANT OUT OF COMPLIANCE', 
#           ]
# theft = ['THEFT PLAIN - PETTY ($950 & UNDER)', 'VEHICLE - STOLEN', 'THEFT FROM MOTOR VEHICLE - PETTY ($950 & UNDER)', 'THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LIVESTK,PROD',
#          'SHOPLIFTING - PETTY THEFT ($950 & UNDER)', 'THEFT FROM MOTOR VEHICLE - GRAND ($400 AND OVER)', 'DOCUMENT FORGERY / STOLEN FELONY',
#          'THEFT, PERSON', 'BIKE - STOLEN', 'EMBEZZLEMENT, GRAND THEFT ($950.01 & OVER)', 'BUNCO, PETTY THEFT', 'SHOPLIFTING-GRAND THEFT ($950.01 & OVER)', 
#          'VEHICLE - ATTEMPT STOLEN', 'DEFRAUDING INNKEEPER/THEFT OF SERVICES, $400 & UNDER',
#         ]
# burglary = ['BURGLARY FROM VEHICLE', 'BURGLARY', 'BURGLARY, ATTEMPTED', 'BURGLARY FROM VEHICLE, ATTEMPTED', ]
# minorCrimes = ['VANDALISM - FELONY ($400 & OVER, ALL CHURCH VANDALISMS)', 'VANDALISM - MISDEAMEANOR ($399 OR UNDER)',  
#             'LETTERS, LEWD  -  TELEPHONE CALLS, LEWD', 'OTHER MISCELLANEOUS CRIME', 'DISTURBING THE PEACE', 'INDECENT EXPOSURE',
#               'THREATENING PHONE CALLS/LETTERS', ]
# violation = ['TRESPASSING', 'VIOLATION OF COURT ORDER', 'VIOLATION OF RESTRAINING ORDER', 'CONTEMPT OF COURT', 'RESISTING ARREST', 
#             'STALKING', ]
# childCrimes = ['CHILD ABUSE (PHYSICAL) - SIMPLE ASSAULT', 'CHILD NEGLECT (SEE 300 W.I.C.)', 'CHILD ANNOYING (17YRS & UNDER)', 
#               'CHILD ABUSE (PHYSICAL) - AGGRAVATED ASSAULT', ]
# arse = ['ARSON']               
# homicide = ['CRIMINAL HOMICIDE']

# crimeTypes = [assault, theft, burglary, minorCrimes, violation, childCrimes, arse, homicide]

# crimeDF.loc[:,'crimeType'] = 'other'

# def get_crimeType(df):
#     if df['Crm Cd Desc'] in assault:
#         return 'Assault'
#     elif df['Crm Cd Desc'] in theft:
#         return 'Theft'
#     elif df['Crm Cd Desc'] in burglary:
#         return 'Burglary'
#     elif df['Crm Cd Desc'] in minorCrimes:
#         return 'Minor crimes'
#     elif df['Crm Cd Desc'] in violation:
#         return 'Violation'
#     elif df['Crm Cd Desc'] in childCrimes:
#         return 'Child Crimes'
#     elif df['Crm Cd Desc'] in arse:
#         return 'Arse'
#     elif df['Crm Cd Desc'] in homicide:
#         return 'Homicide'
#     else:
#         return 'Other'

# crimeDF['crimeType'] = crimeDF.apply(get_crimeType, axis = 1)

In [ ]:
# import plotly.io as pio

# data = [dict(
#   type = 'scatter',
#   x = crimeDF['DATE'],
#   y = crimeDF['crimeType'],
#   transforms = [dict(
#     type = 'aggregate',
#     groups = crimeDF['crimeType'],
#     aggregations = [dict(
#         target = 'y', func = 'sum', enabled = True),
#     ]
#   )]
# )]

# fig_dict = dict(data=data)

# pio.show(fig_dict, validate=False)

In [ ]:
# crimeTypes_list = crimeTypesMonthDF.columns

# data_sectors = [dict(type='scatter',
#                      x=crimeTypesMonthDF.index,
#                      y=crimeTypesMonthDF[crimeType],
#                      name=crimeType)
#                             for crimeType in crimeTypes_list]

# layout_sectors = dict(title=dict(text='Number of Crimes'),
#                       xaxis=dict(title='Date'),
#                       yaxis=dict(title='# of crime'),
#                       paper_bgcolor='rgba(0,0,0,0)',
#                       plot_bgcolor='rgba(0,0,0,0)',)

# fig_sectors = go.Figure(data=data_sectors, layout=layout_sectors)

# fig_sectors.show()